name: PR Tests

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files

  generate-jobs:
    name: Generate Jobs
    needs: [pre-commit]
    runs-on: ubuntu-latest
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - id: set-matrix
        shell: bash
        run:
          echo session=$(nox --json -l | jq -c '[.[].session]') | tee --append
          $GITHUB_OUTPUT

  checks:
    name: Session ${{ matrix.session }}
    needs: [generate-jobs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-jobs.outputs.session) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          miniforge-version: latest
      - uses: wntrblm/nox@main
      - run: nox -s "${{ matrix.session }}"

  check_py38:
    name: Check valid py3.8 code
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m compileall -q src tests
